open-ai:
  apiKey: [Openai Secret]
  maxContext: 15
  holdingTime: 10
  maxTokens: 1024
  temperature: 1
  model: GPT_3_5_TURBO

wechat:
  cp:
    token: [自建应用-API接收消息页面-Token]
    encodingAESKey: [自建应用-API接收消息页面-TokEncodingAESKey]
    corpSecret: [自建应用-详情页-Secret]
    agentId: [自建应用-应用管理详情页-AgentId]
    corpID: [企业微信管理后台-我的企业-企业信息-最下面的企业ID]
    messageLength: 1024
    waitTime: 500